baseURL = "https://alexmartins.work/"
languageCode = 'en-us'
title = 'argoblog'
theme = "shibui"

[params]
  author = "Alex Martins"
  email = "hello@alexmartins.work"
  mainSections = ["posts"]

[permalinks]
  posts  = "/posts/:slug/"
  poemas = "/poemas/:slug/"


[menu]
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 1
  [[menu.main]]
  name = "Poemas"
  url = "/poemas/"
  weight = 2
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3
